FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
		clang-tidy \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
